# Generated by Django 3.2.4 on 2021-06-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='img/users/'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=70, null=True, verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='user',
            name='direction',
            field=models.CharField(max_length=70, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=70, null=True, verbose_name='Telefono'),
        ),
    ]
