# Generated by Django 3.2.4 on 2021-06-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210628_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'permissions': (('can_view_cart', 'User can view cart'), ('can_add_cart', 'User can add products to cart'), ('can_delete_cart', 'User can delete products of cart')), 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='img/users/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='user',
            name='direction',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Telefono'),
        ),
    ]
