# Generated by Django 3.2.4 on 2021-06-16 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('-id',)},
        ),
    ]
